# Generated by Django 5.0 on 2026-01-18 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackinghistory',
            name='expense_type',
            field=models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], max_length=10),
        ),
    ]
